all: task.js server/fileIO.js server/httpController.js client/controller.js
task.js: task.ts
	tsc task.ts
server/fileIO.js: server/fileIO.ts
	tsc server/fileIO.ts
server/httpController.js: server/httpController.ts
	tsc server/httpController.ts
client/controller.js: client/controller.ts
	tsc client/controller.ts